<NMath> Add new functions to libnmath
VisorFolks/cyancore pull request #174
Opened 2022-12-25 15:05 UTC by akashkollipara

* Arithmetic
  - isPrime
* Complex Math
  - new datatypes

Issue #173

2022-12-26 05:55 UTC, pranjalchanda08 commented
resolve the code smells

2022-12-26 05:58 UTC, pranjalchanda08 requested changes
Resolve the code smells

2022-12-26 12:42 UTC, akashkollipara commented
> Resolve the code smells

done... nothing major just few typcast (intended) warning

2022-12-27 04:40 UTC, pranjalchanda08 approved these changes

2022-12-27 04:40 UTC, merged