Add Test Applications
VisorFolks/cyancore pull request #200
Opened 2023-01-04 16:00 UTC by pranjalchanda08

2023-01-04 16:03 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/cc_os_heap.c
> +void * cc_os_malloc(size_t size)
@akashkollipara  These are temporary changes

2023-01-05 02:34 UTC, akashkollipara commented on .vscode/settings.json
> -{
why delete this file?

2023-01-05 02:34 UTC, akashkollipara commented on mk/path.mk
> +CC_OS_ROOT	:= $(SRC)/include/visor/terravisor/cc_os
dont use this... use $(GET_PATH)

2023-01-05 05:01 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/cc_os_sched.c
> +			ptr->wait_res.wait_on_resource = CC_OS_FALSE;
It is just a convention being used by CC_OS and within CC_OS. In upper levels we dont have any such macros.

2023-01-05 05:04 UTC, pranjalchanda08 commented on projects/demo_cc_os.src/project.c
> +CC_TASK_DEF( TASK_A, task_handler, NULL, 10, 100);
These are not static allocation. Please look into the MACRO expansion. That is just instance initialization. The allocation happens during cc_os_task_add()

2023-01-05 05:26 UTC, pranjalchanda08 commented on .vscode/settings.json
> -{
By Mistake. Reverted

2023-01-08 11:32 UTC, akashkollipara requested changes

2023-01-08 11:32 UTC, akashkollipara commented on .vscode/settings.json
> -        "*.{S,S.old,S.dev.S.temp,S.tmp,s.old,s.temp,s.tmp,s.dev,asm,asm.old,asm.dev.asm.temp,asm.tmp,inc,inc.old,inc.temp,inc.tmp,ld,ld.old,ld.temp,ld.tmp,ld.sx,ld.sx.old,ld.sx.temp,ld.sx.tmp,lst}":
undo this change

2023-01-12 16:58 UTC, akashkollipara requested changes

2023-01-12 16:58 UTC, akashkollipara commented on projects/demo_cc_os.src/build.mk
> +# Primary Author	: Pranjal Chdanda [pranjalchanda08@gmail.com]
Typo...

2023-01-12 16:58 UTC, akashkollipara commented on projects/demo_cc_os.src/project.c
> + * Copyrights (C) 2019, Cyancore Team
year...

2023-01-12 16:58 UTC, akashkollipara commented on projects/demo_cc_os.src/project.c
> +}
why dont you exit after say 5 iters and see if OS works fine without crashing?

2023-01-12 16:58 UTC, akashkollipara commented on projects/demo_cc_os_avr/config.mk
> +CONSOLE_SERIAL	:= 0
you will need these...

2023-01-12 16:58 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_tasks.c
> +#endif
I think stack_ptr should be inside `#if`
normally the program config won't change.

Use case may vary and so will the args.

2023-01-12 16:58 UTC, akashkollipara commented
Minor Comments... otherwise LGTM!

2023-01-13 09:10 UTC, pranjalchanda08 commented on projects/demo_cc_os.src/project.c
> +}
This kinda case is not handled. We need to see what happens when the task returns. In FreeRTOS the task handler return is not supported as well it crashes as much as I know. If we want to add that then we need to see for some algorithm addition to identify that and handle that.

2023-01-13 09:13 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/cc_os_tasks.c
> +#endif
So basically the stack_ptr is an input to the functions, that input is only applicable if the user configures the OS as static. but lets say the user codes it with static first and then switches to dynamic then the compilation will fail.

2023-01-13 09:46 UTC, pranjalchanda08 commented on projects/demo_cc_os_avr/config.mk
> +CONSOLE_SERIAL	:= 0
I am turning this on for Risc-v not for avr it would take lot of memory. Its user's choice.

2023-01-13 13:18 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_tasks.c
> +#endif
True... but i dont think such use case will ever come up with OS configs...

2023-01-13 13:19 UTC, akashkollipara commented on projects/demo_cc_os.src/project.c
> +}
Alright...

2023-01-13 13:19 UTC, akashkollipara approved these changes
Approving this PR... we can address the rest later.

2023-01-13 13:20 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_tasks.c
> +#endif
Marking it resolved... but this can come up later.

2023-01-13 13:20 UTC, merged