<CC_OS> Task defination re-structuring
VisorFolks/cyancore pull request #202
Opened 2023-01-05 08:21 UTC by pranjalchanda08

Re-structuring of CC_OS TASK definition done.

2023-01-08 11:30 UTC, akashkollipara requested changes

2023-01-08 11:30 UTC, akashkollipara commented on projects/demo_cc_os.src/project.c
> +cc_os_task_t * Task_C;
static cc_os... ?

2023-01-08 11:30 UTC, akashkollipara commented on src/include/visor/terravisor/cc_os/cc_os_config.mk
>  $(eval $(call add_define,CC_OS_POWER_SAVE_EN))
Move this file to `src/visor/terravisor/cc_os/config.mk`

2023-01-08 11:30 UTC, akashkollipara commented on src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
> +	uintptr_t args_ptr;					///> Task Call argument ptr
Just a questions... why don't we make it std that we dont pass to callbacks/tasks/thread, etc...
instead we can write a function to retrieve params.

2023-01-08 11:30 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_tasks.c
> +#if CC_OS_DYNAMIC == CC_OS_FALSE
Use normal FALSE or TRUE

2023-01-08 11:49 UTC, pranjalchanda08 commented on src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
> +	uintptr_t args_ptr;					///> Task Call argument ptr
See if we do that them it is very different with how the pthread or any other standard calls are.

2023-01-10 06:20 UTC, pranjalchanda08 commented on src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
> +	uintptr_t args_ptr;					///> Task Call argument ptr
Resolving for now with an open idea. Lets brainstorm over this.

2023-01-10 11:04 UTC, pranjalchanda08 reviewed
Resolved Comments

2023-01-10 11:06 UTC, pranjalchanda08 commented
Closes : #201

2023-01-11 13:02 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_sched.c
> +	const long int * wait_res = (long int *)ptr->wait_res.wait_on_resource;
`int` should be fine!

2023-01-11 13:06 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_sched.c
>  	switch (link_type)
why not if-elseif-else...
switch-case makes a table in rodata section. it's expensive for ram

2023-01-11 13:06 UTC, akashkollipara commented on src/visor/terravisor/services/kernel/cc_os_sem.c
>  #endif
same goes for rest.

2023-01-11 14:28 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/cc_os_sem.c
>  #endif
Let us discuss this. And keep it an open item for now.

2023-01-12 07:07 UTC, merged