<LibC> Add support for float in printf
VisorFolks/cyancore pull request #205
Opened 2023-01-13 15:39 UTC by akashkollipara

- Added float support in printf. Without format specifier float prints 5 fractional places.
- Removed snprintf as it is outdated.

Issue: #154

2023-01-13 15:41 UTC, akashkollipara commented
Functional Test passed on RISC-V

2023-01-13 15:42 UTC, akashkollipara commented
AVR Target seems to miss out on float support... Pushing another path to fix AVR target.

2023-01-13 17:04 UTC, akashkollipara commented
Tested on qemu AVR. Float engine works!

2023-01-14 08:43 UTC, pranjalchanda08 requested changes
Minor changes else LGTM!

2023-01-14 08:43 UTC, pranjalchanda08 commented on src/lib/libc/printf.c
> +	char *str, ch;
Use separate line for declaring the new variables.

2023-01-14 08:44 UTC, akashkollipara commented on src/lib/libc/printf.c
> +	char *str, ch;
Any specific reason ?

2023-01-14 11:30 UTC, pranjalchanda08 commented on src/lib/libc/printf.c
> +	char *str, ch;
It is as per the standards! 
![image](https://user-images.githubusercontent.com/40349163/212469727-7963a413-5a80-4225-a1f7-8040bd7b8f24.png)

Anyhow it is deactivated on the sonarcloud I feel.

2023-01-14 12:01 UTC, pranjalchanda08 approved these changes

2023-01-14 12:01 UTC, merged