<HELIOS> Add mutex support
VisorFolks/cyancore pull request #227
Opened 2023-02-04 16:05 UTC by Dybios

Issue: #184

Signed-off-by: Dybios <dibyajyoti.samal@gmail.com>

2023-02-11 12:53 UTC, pranjalchanda08 requested changes
Please remove the Sonar Cloud code smell.

2023-02-11 12:53 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	HELIOS_ASSERT_IF_FALSE((mutex_ptr != HELIOS_NULL_PTR && mutex_ptr->mutex_init != false));
Split this into two different checks so that to is easy to detect the reason while debugging.

2023-02-11 12:53 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +				mutex_ptr->mutex_val--; /* TODO: Check signage in case of mutex recursion */
complete the TODO.

2023-02-11 12:53 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
When you lock the mutex you may want to have the lock_task assigned to current task.

2023-02-11 12:53 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	HELIOS_ASSERT_IF_FALSE((mutex_ptr != HELIOS_NULL_PTR && mutex_ptr->mutex_init != false));
Same as above!

2023-02-11 14:20 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	if (mutex_ptr->mutex_val == false)
This can be even lesser than zero for recursive lock.

2023-02-11 14:23 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
It is recommended to decrement in a single place. Use a flag variable instead to check if the lock can be acquired or not. Then the signage check can be done in a single palce.

2023-02-11 14:24 UTC, pranjalchanda08 commented on src/include/visor/terravisor/helios/helios_mutex.h
> +
Remove unnecessary linefeeds and spaces. There shall be only one LF after each function declaration not after any docstring.

2023-02-11 14:25 UTC, pranjalchanda08 requested changes

2023-02-11 14:25 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +status_t helios_mutex_create	(helios_mutex_t ** mutex_ptr)
Please add more logical comments to help user read the code flow.

2023-02-12 09:04 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	HELIOS_ASSERT_IF_FALSE((mutex_ptr != HELIOS_NULL_PTR && mutex_ptr->mutex_init != false));
Done. May need to be done in semaphore implementation as well.

2023-02-12 09:05 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +				mutex_ptr->mutex_val--; /* TODO: Check signage in case of mutex recursion */
Done. Updated the var to a signed int to allow negative values.

2023-02-12 09:05 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
Fixed the same. Thanks for pointing it out.

2023-02-12 09:06 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	HELIOS_ASSERT_IF_FALSE((mutex_ptr != HELIOS_NULL_PTR && mutex_ptr->mutex_init != false));
Fixed

2023-02-12 09:08 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	if (mutex_ptr->mutex_val == false)
Fixed. Now checking if mutex_val isn't the init_val instead. Also fixed the init_val to 1, was mistakenly set to zero.

2023-02-12 09:08 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
Done.

2023-02-12 09:08 UTC, Dybios commented on src/include/visor/terravisor/helios/helios_mutex.h
> +
Fixed.

2023-02-12 09:09 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +status_t helios_mutex_create	(helios_mutex_t ** mutex_ptr)
Updated the @note to add more description. Please check and let me know if any changes needed.

2023-02-12 09:48 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
Fixed. Thanks for pointing this out.

2023-02-12 09:49 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +status_t helios_mutex_create	(helios_mutex_t ** mutex_ptr)
Added more comments to help readability.

2023-02-12 09:50 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +status_t helios_mutex_create	(helios_mutex_t ** mutex_ptr)
Need to add internal comments as well for each if block.

2023-02-12 10:01 UTC, pranjalchanda08 requested changes
One comment yet to be resolved. Else LGTM!

2023-02-12 10:02 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	if (mutex_ptr->mutex_val == false)
I do not see any changes yet. May be missed to commit the change.

2023-02-12 10:13 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +static const int init_val = 1;
Use a MACRo Not Magic numbers. Please change the same if used anywhere else as well.

2023-02-12 11:48 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
I have added the decrement inside the else, and the if block holds the error condition. It only locks if the lock_task is the curr_task. I can see the change on my end. Please confirm.

2023-02-12 11:52 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
The line number you are pointing to is already enclosed in the task check conditional. It only recursively locks if the locking task is the current task.
Though, I have updated the outer else to your comment since it was missing that.

2023-02-12 11:58 UTC, pranjalchanda08 commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		(*mutex_ptr)->lock_task = g_sched_ctrl.curr_task;
This is wrong. The mutex is a shared object and can be locked by any thread who has the priority/resource availability.

2023-02-19 18:29 UTC, Dybios commented
> One comment yet to be resolved. Else LGTM!

@pranjalchanda08 Updated and pushed as per your inputs, please do review. Seems like there's a build failure due to the semaphore commit. It would need to be fixed for this PR to pass the build check.

Thanks

2023-02-26 04:48 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		mutex_ptr->mutex_val--;
Pushed a commit to fix according to this comment. Added this assignment whenever the lock flag is set. Thanks

2023-02-26 04:51 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +static const int init_val = 1;
Used a #define instead. Pushed this as a new commit as well.

2023-02-26 04:52 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +		(*mutex_ptr)->lock_task = g_sched_ctrl.curr_task;
Fixed. Pushed as a new commit.

2023-02-26 04:53 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +	if (mutex_ptr->mutex_val == false)
Updated these changes in the newer commits. Please check and let me know if it's reflected. I'll resolve this

2023-02-26 04:54 UTC, Dybios commented on src/visor/terravisor/services/kernel/helios_mutex.c
> +			HELIOS_ERR("Mutex initialized by another task");
Fixed in the newest commit.

2023-02-26 05:02 UTC, pranjalchanda08 approved these changes
All Comments resolved. LGTM!

2023-02-26 05:03 UTC, merged