<Docs> Updated help
VisorFolks/cyancore pull request #244
Opened 2023-11-20 17:30 UTC by akashkollipara

Issue: #243

2023-11-21 18:26 UTC, akashkollipara commented
New `make help` view

![image](https://github.com/VisorFolks/cyancore/assets/24636040/ed98cfb4-3e44-4a35-9a52-970acd596e41)

2023-11-21 18:28 UTC, akashkollipara commented
Added new demo target `make qemu_test`.

![image](https://github.com/VisorFolks/cyancore/assets/24636040/f5e3054e-f8b3-445f-ae7a-b5ef7643f49c)

2023-11-21 19:02 UTC, pranjalchanda08 approved these changes

2023-11-22 07:22 UTC, shubhangi47 requested changes

2023-11-22 07:22 UTC, shubhangi47 commented on mk/help.mk
> +\n\
Add illustration on for better understanding.

2023-11-22 15:11 UTC, shubhangi47 approved these changes

2023-11-22 15:11 UTC, merged