Bugfix/akashkollipara/status codes
VisorFolks/cyancore pull request #266
Opened 2023-12-24 14:01 UTC by akashkollipara

2023-12-25 12:06 UTC, pranjalchanda08 requested changes

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/mega_avr/common/hal/spi/spi.c
> +	RET_ON_FAIL(port, error_inval_pointer);
Create a Wrapper Macro for Pointer and Param assert. That would reduce repetitive codes.

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/mega_avr/common/hal/wdt/wdt.c
> +status_t wdt_srd(const wdt_port_t *port _UNUSED)
Why dont we have a Pointer check here?

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/mega_avr/common/hal/wdt/wdt.c
> -	assert(port);
Why dont we have a Pointer check here?

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/mega_avr/common/hal/wdt/wdt.c
>  void wdt_hush(const wdt_port_t *port _UNUSED)
Why dont we have a Pointer check here?

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/driver/interrupt/plic/plic.c
> +	RET_ON_FAIL(id && handler,);
What is the return here? How does it build?

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/driver/sysclk/sysclk_prci/sysclk_prci.c
> +	RET_ON_FAIL(port && port->baddr && port->base_clk,);
Return not specified

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/driver/sysclk/sysclk_prci/sysclk_prci.c
> +	RET_ON_FAIL(port && port->baddr && port->base_clk,);
Return not specified

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/sifive/common_fe310/hal/clint/clint.c
>  	if(core_id >= N_CORES)
You can use MACRO here as well rather than if case

2023-12-25 12:06 UTC, pranjalchanda08 commented on src/platform/sifive/common_fe310/hal/clint/clint.c
>  	if(core_id >= N_CORES)
You can use MACRO here as well rather than if case

2023-12-25 15:07 UTC, akashkollipara commented on src/platform/mega_avr/common/hal/wdt/wdt.c
> +status_t wdt_srd(const wdt_port_t *port _UNUSED)
we dont need to... hence I've put _UNUSED

2023-12-25 15:08 UTC, akashkollipara commented on src/platform/mega_avr/common/hal/wdt/wdt.c
>  void wdt_hush(const wdt_port_t *port _UNUSED)
Same reason as mentioned earlier...

2023-12-25 15:08 UTC, akashkollipara commented on src/driver/sysclk/sysclk_prci/sysclk_prci.c
> +	RET_ON_FAIL(port && port->baddr && port->base_clk,);
Not needed. Its a void function.

2023-12-25 15:08 UTC, akashkollipara commented on src/driver/interrupt/plic/plic.c
> +	RET_ON_FAIL(id && handler,);
void function.

2023-12-28 04:20 UTC, akashkollipara commented on src/platform/mega_avr/common/hal/wdt/wdt.c
> -	assert(port);
Marked unused.

2023-12-28 04:21 UTC, akashkollipara commented on src/driver/sysclk/sysclk_prci/sysclk_prci.c
> +	RET_ON_FAIL(port && port->baddr && port->base_clk,);
Static and void function, pointer validation is done in the caller function.
actually we can remote it.

2023-12-31 05:54 UTC, akashkollipara commented on src/platform/mega_avr/common/hal/spi/spi.c
> +	RET_ON_FAIL(port, error_inval_pointer);
wouldn't that be overkill?

2023-12-31 12:48 UTC, pranjalchanda08 commented on src/platform/mega_avr/common/hal/spi/spi.c
> +	RET_ON_FAIL(port, error_inval_pointer);
Nope rather you are writing less as this return is being done quiet much frequently. So, ur .c file size would lower down with a better aesthetic code.

2023-12-31 12:48 UTC, pranjalchanda08 commented on src/driver/sysclk/sysclk_prci/sysclk_prci.c
> +	RET_ON_FAIL(port && port->baddr && port->base_clk,);
ok

2024-01-03 06:04 UTC, akashkollipara commented on src/platform/sifive/common_fe310/hal/clint/clint.c
>  	if(core_id >= N_CORES)
Arg is run time... macro wont work. haan if based macro will, but its same.

2024-01-03 06:08 UTC, pranjalchanda08 commented on src/platform/sifive/common_fe310/hal/clint/clint.c
>  	if(core_id >= N_CORES)
RET_ON_FAIL(core_id < N_CORES, err_core);

Why won't this work???
N_CORES is a macro only. 
This will surely work.

2024-01-03 06:18 UTC, akashkollipara commented on src/platform/sifive/common_fe310/hal/clint/clint.c
>  	if(core_id >= N_CORES)
ok...

2024-01-03 13:51 UTC, pranjalchanda08 approved these changes

2024-01-03 13:51 UTC, pranjalchanda08 commented
LGTM!

2024-01-03 13:52 UTC, merged