<LibNMath> Added new function to neomath library
VisorFolks/cyancore pull request #41
Opened 2021-09-26 19:12 UTC by akashkollipara

2021-09-26 19:20 UTC, akashkollipara commented
Do not close or proceed with merging this yet...
Planning to add Matrix manipulation algorithms.

Do should i raise another PR? @VisorFolks/cc-admin

2021-10-04 05:33 UTC, pranjalchanda08 commented
I can not see Jenkins details:
![image](https://user-images.githubusercontent.com/40349163/135799005-c5bf33bf-7f00-462e-9d26-84af302432fb.png)

2021-10-04 05:41 UTC, akashkollipara commented
yes you cannot see as u need the ngrok link...

2021-10-04 06:00 UTC, pranjalchanda08 commented
> yes you cannot see as u need the ngrok link... you can only see the status mark... details we cant.

Do is it because of continuous changing of links?

2021-10-04 06:06 UTC, akashkollipara commented
> > yes you cannot see as u need the ngrok link... you can only see the status mark... details we cant.
> 
> So is it because of continuous changing of links?

Yes precisely!

2021-10-04 06:19 UTC, pranjalchanda08 requested changes

2021-10-04 06:19 UTC, pranjalchanda08 commented on jenkins.pipe
> +				sh 'rm -rf toolchain'
why do we need to remove the toolchain in clean?

2021-10-04 06:19 UTC, pranjalchanda08 commented on src/lib/libnmath/nmath.c
> +	return (b == 0) ? a: gcd(b, (a % b));
Is it possible to not use recursion? for large value of a and b stack smash can occur.

2021-10-04 06:20 UTC, pranjalchanda08 commented
> > > yes you cannot see as u need the ngrok link... you can only see the status mark... details we cant.
> > 
> > 
> > So is it because of continuous changing of links?
> 
> Yes precisely!

Might be post the logs of CI?

2021-10-04 06:45 UTC, akashkollipara commented on src/lib/libnmath/nmath.c
> +	return (b == 0) ? a: gcd(b, (a % b));
Well... this according to code consumes stack.
but with -Os flag we are trying to optimize use of memory.
So when you look at disassembly, this is just a while loop.

2021-10-04 06:46 UTC, akashkollipara commented on jenkins.pipe
> +				sh 'rm -rf toolchain'
Why to retain when we can freshly checkout the TC for every build. It saves space on build disk also.

2021-10-04 06:47 UTC, pranjalchanda08 commented on src/lib/libnmath/nmath.c
> +	return (b == 0) ? a: gcd(b, (a % b));
have u tested it with larger numbers?

2021-10-04 06:52 UTC, pranjalchanda08 commented on jenkins.pipe
> +				sh 'rm -rf toolchain'
Wont it take time to pull again and again?

2021-10-04 06:58 UTC, akashkollipara commented on src/lib/libnmath/nmath.c
> +	return (b == 0) ? a: gcd(b, (a % b));
![image](https://user-images.githubusercontent.com/24636040/135806446-4d506160-3bd7-4a8a-8d51-6dc2bf32ebde.png)
This is disasm of function with long, long numbers.

2021-10-04 06:59 UTC, akashkollipara commented on jenkins.pipe
> +				sh 'rm -rf toolchain'
nope... 7-8 sec is all it needs

2021-10-04 06:59 UTC, pranjalchanda08 commented on src/lib/libnmath/nmath.c
> +	return (b == 0) ? a: gcd(b, (a % b));
ok then this makes sense.

2021-10-04 11:29 UTC, pranjalchanda08 approved these changes

2021-10-04 11:30 UTC, merged